apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: paperlab
  namespace: paperlab
spec:
  selector:
    matchLabels:
      monitor: paperlab
  endpoints:
  - port: http
    path: /metrics
    interval: 5s
